<?php

/**
 * @file
 * gelf.module
 *
 */

/**
 * Implements hook_permission()
 *
 * Allows admins to control access to gelf settings.
 */
function gelf_permission() {
  return array(
    'administer gelf' => array(
      'title' => t('administer gelf'),
      'description' => t('Manage graylog2 host settings'),
    ),
  );
}

/**
 * Implement hook_watchdog().
 */
function gelf_watchdog($entry) {
  if (!gelf_require()) {
    if(user_access('administer gelf')) {
      drupal_set_message(t('GELF module requires the GELF PHP library to be installed.  View the README for installation instructions.'), 'error');
    }
    return;
  }

  $host = variable_get('gelf_host', 'localhost');
  $port = variable_get('gelf_port', 12201);
  $gelf = new GELFMessage();
  $message = filter_xss(is_null($entry['variables']) ? $entry['message'] : strtr($entry['message'], $entry['variables']));
  $short_msg_length = 100;
  if(strlen($message) > $short_msg_length) {
    $short_message = preg_replace('/\s+?(\S+)?$/u', '', substr($message, 0, $short_msg_length));
  }
  else {
    $short_message = $message;
  }
  $username = isset($entry['user']->name) ? $entry['user']->name : variable_get('anonymous', t('Anonymous'));
  $gelf->setShortMessage($short_message);
  $gelf->setFullMessage($message);
  $gelf->setHost(php_uname('n'));
  $gelf->setFacility($entry['type']);
  $gelf->setLevel($entry['severity']);
  $gelf->setTimestamp($entry['timestamp']);
  $gelf->setAdditional("Referer", $entry['referer']);
  $gelf->setAdditional("Link", $entry['link']);
  $gelf->setAdditional("Username", $username);
  $gelf->setAdditional("Uid", $entry['user']->uid);
  $gelf->setAdditional("Request_uri", $entry['request_uri']);
  $gelf->setAdditional("Server_host", $_SERVER['HTTP_HOST']);
  $gelf->setAdditional("Client_host", $entry['ip']);

  // Add additional fields configured with the interface.
  $additional = variable_get('gelf_fields', array());
  foreach ($additional as $field) {
    $gelf->setAdditional($field['field'], $field['value']);
  }

  try {
    $publisher = new GELFMessagePublisher($host, $port);
    $publisher->publish($gelf);
  }
  catch (UnexpectedValueException $e) {
    if(user_access('administer gelf')) {
      drupal_set_message(t('Failed to publish gelf message: %message', array('%message' => $e->getMessage())), 'error');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gelf_form_system_logging_settings_alter(&$form, $form_state) {
  // Add submit hook to handle additional fields.
  $form['#submit'][] = 'gelf_form_system_logging_settings_submit';

  $form['gelf'] = array(
    '#type' => 'fieldset',
    '#title' => t('GELF Settings'),
    '#tree' => FALSE,
    '#collapsible' => TRUE,
  );

  $form['gelf']['gelf_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Graylog2 host'),
    '#default_value' => variable_get('gelf_host', 'localhost'),
  );
  $form['gelf']['gelf_port'] = array(
    '#type' => 'textfield',
    '#title' => t('Graylog2 GELF port'),
    '#default_value' => variable_get('gelf_port', 12201),
  );

  $form['gelf']['gelf_fields'] = array(
    '#type' => 'fieldset',
    '#title' => t('Custom fields'),
    '#description' => t('You can add additional fields to your gelf messages.' .
      'They will be added to every log message. Submit the form to add more ' .
      'than three fields.'),
    '#tree' => TRUE,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $fields = variable_get('gelf_fields', array());

  // merge 3 new empty fields
  $fields = array_merge($fields, array(
    array('field' => '', 'value' => ''),
    array('field' => '', 'value' => ''),
    array('field' => '', 'value' => ''),
  ));

  $i = 1;
  foreach ($fields as $field) {
    $form['gelf']['gelf_fields']['field_' . $i] = array(
      '#type' => 'fieldset',
      '#title' => $field['field'] ? t('Field') . ': ' . $field['field'] : t('New field'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#tree' => TRUE,
      'field' => array(
        '#type' => 'textfield',
        '#title' => t('Field name'),
        '#default_value' => $field['field'],
      ),
      'value' => array(
        '#type' => 'textfield',
        '#title' => t('Value'),
        '#default_value' => $field['value'],
      )
    );

    ++$i;
  }


  if (!gelf_require()) {
    drupal_set_message(t('GELF module requires the GELF PHP library to be installed.  View the README for installation instructions.'), 'error');
  }

  return $form;
}

function gelf_form_system_logging_settings_submit(&$form, $form_state) {
  $values = $form_state['values'];

  $fields = array();

  foreach ($values['gelf_fields'] as $field_spec) {
    $field_name = $field_spec['field'];
    $value = $field_spec['value'];

    if (strlen($field_name) > 0 || strlen($value) > 0) {
      $fields[] = $field_spec;
    }
  }

  variable_set('gelf_fields', $fields);
}

/**
 * Include gelf-php library.
 *
 * @return boolean
 */
function gelf_require() {
  // Check if the classes already exist and allow existing autoloaders.
  if (class_exists('GELFMessage') && class_exists('GELFMessagePublisher')) {
    return TRUE;
  }

  // Check module for Composer autoload file.
  if (@include_once(dirname(__FILE__) . '/vendor/autoload.php')) {
    return TRUE;
  }

  // Use Libraries API to load it.
  if (module_exists('libraries')) {
    $gelfmsg_path = libraries_get_path('gelf-php') . '/GELFMessage.php';
    $gelfpub_path = libraries_get_path('gelf-php') . '/GELFMessagePublisher.php';

    // Check if the php-gelf library is available
    if (file_exists(DRUPAL_ROOT . '/' . $gelfmsg_path) && file_exists(DRUPAL_ROOT . '/' . $gelfpub_path)) {
      require_once DRUPAL_ROOT . '/' . $gelfmsg_path;
      require_once DRUPAL_ROOT . '/' . $gelfpub_path;
      return TRUE;
    }
  }

  return FALSE;
}
